version: "3"

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - hillel
  db:
    image: postgres
    restart: always
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_DB=hillel
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    networks:
      - hillel
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - hillel
networks:
  hillel:
